[program:xml-mapper-scheduler]
command=/usr/bin/php /var/www/xml-mapper/current/artisan schedule:work
directory=/var/www/xml-mapper/current
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/xml-mapper/scheduler.log
stopwaitsecs=60
